// Chapter 01 — A Dark Room
// Post-apocalyptic winter survival. A dying fire. A cold room. The world outside is gone.

import {
  ChapterConfig,
  ResourceDef,
  BuildingDef,
  CraftRecipeDef,
  PhaseConfig,
} from '@/types/chapter';
import { Phase } from '@/types/game';
import { npcs } from './npcs';
import { events } from './events';
import { mapConfig } from './map';

// ---------------------------------------------------------------------------
// Resources
// ---------------------------------------------------------------------------

const resources: ResourceDef[] = [
  {
    id: 'wood',
    name: 'wood',
    description: 'dry timber. burns well.',
    category: 'raw',
    baseCap: 200,
    capGrowth: 100,
    unlockCondition: { type: 'always' },
    hidden: false,
  },
  {
    id: 'fur',
    name: 'fur',
    description: 'thick animal pelts. warm.',
    category: 'raw',
    baseCap: 100,
    capGrowth: 50,
    unlockCondition: { type: 'building', target: 'trap', value: 1 },
    hidden: true,
  },
  {
    id: 'meat',
    name: 'meat',
    description: 'raw meat. needs to be preserved.',
    category: 'raw',
    baseCap: 100,
    capGrowth: 50,
    unlockCondition: { type: 'building', target: 'trap', value: 1 },
    hidden: true,
  },
  {
    id: 'scales',
    name: 'scales',
    description: 'hard reptilian scales from the deep traps.',
    category: 'raw',
    baseCap: 50,
    capGrowth: 25,
    unlockCondition: { type: 'building', target: 'trap', value: 3 },
    hidden: true,
  },
  {
    id: 'teeth',
    name: 'teeth',
    description: 'sharp teeth. useful for crafting.',
    category: 'raw',
    baseCap: 50,
    capGrowth: 25,
    unlockCondition: { type: 'building', target: 'trap', value: 3 },
    hidden: true,
  },
  {
    id: 'cloth',
    name: 'cloth',
    description: 'woven strips of fabric. rough but functional.',
    category: 'refined',
    baseCap: 80,
    capGrowth: 40,
    unlockCondition: { type: 'building', target: 'tannery', value: 1 },
    hidden: true,
  },
  {
    id: 'leather',
    name: 'leather',
    description: 'treated hide. durable.',
    category: 'refined',
    baseCap: 80,
    capGrowth: 40,
    unlockCondition: { type: 'building', target: 'tannery', value: 1 },
    hidden: true,
  },
  {
    id: 'curedMeat',
    name: 'cured meat',
    description: 'smoked and salted. lasts a long time.',
    category: 'refined',
    baseCap: 100,
    capGrowth: 50,
    unlockCondition: { type: 'building', target: 'smokehouse', value: 1 },
    hidden: true,
  },
  {
    id: 'iron',
    name: 'iron',
    description: 'crude ore. cold and heavy.',
    category: 'refined',
    baseCap: 80,
    capGrowth: 40,
    unlockCondition: { type: 'building', target: 'ironMine', value: 1 },
    hidden: true,
  },
  {
    id: 'coal',
    name: 'coal',
    description: 'black rock. burns hot.',
    category: 'refined',
    baseCap: 80,
    capGrowth: 40,
    unlockCondition: { type: 'building', target: 'coalMine', value: 1 },
    hidden: true,
  },
  {
    id: 'sulphur',
    name: 'sulphur',
    description: 'yellow powder. smells of ruin.',
    category: 'refined',
    baseCap: 40,
    capGrowth: 20,
    unlockCondition: { type: 'building', target: 'coalMine', value: 3 },
    hidden: true,
  },
  {
    id: 'steel',
    name: 'steel',
    description: 'forged metal. strong.',
    category: 'crafted',
    baseCap: 60,
    capGrowth: 30,
    unlockCondition: { type: 'building', target: 'steelworks', value: 1 },
    hidden: true,
  },
  {
    id: 'alloy',
    name: 'alloy',
    description: 'strange metal from the old world. light and impossibly strong.',
    category: 'endgame',
    baseCap: 30,
    capGrowth: 10,
    unlockCondition: { type: 'building', target: 'steelworks', value: 3 },
    hidden: true,
  },
  {
    id: 'bone',
    name: 'bone',
    description: 'bleached white. surprisingly sturdy.',
    category: 'raw',
    baseCap: 60,
    capGrowth: 30,
    unlockCondition: { type: 'building', target: 'trap', value: 1 },
    hidden: true,
  },
  {
    id: 'herb',
    name: 'herbs',
    description: 'bitter roots and leaves. medicinal.',
    category: 'raw',
    baseCap: 40,
    capGrowth: 20,
    unlockCondition: { type: 'phase', target: 'settlement' },
    hidden: true,
  },
  {
    id: 'water',
    name: 'water',
    description: 'clean water. precious.',
    category: 'raw',
    baseCap: 60,
    capGrowth: 30,
    unlockCondition: { type: 'phase', target: 'wild' },
    hidden: true,
  },
];

// ---------------------------------------------------------------------------
// Buildings
// ---------------------------------------------------------------------------

const buildings: BuildingDef[] = [
  {
    id: 'trap',
    name: 'trap',
    description: 'a simple snare. catches small things.',
    category: 'gathering',
    maxLevel: Infinity,
    costs: [
      { level: 1, resources: { wood: 10 } },
      { level: 2, resources: { wood: 30 } },
      { level: 3, resources: { wood: 60, fur: 5 } },
      { level: 4, resources: { wood: 100, fur: 10 } },
      { level: 5, resources: { wood: 150, leather: 5 } },
      { level: 6, resources: { wood: 200, leather: 10 } },
      { level: 7, resources: { wood: 300, leather: 20, iron: 5 } },
      { level: 8, resources: { wood: 400, iron: 10 } },
      { level: 9, resources: { wood: 500, iron: 20 } },
      { level: 10, resources: { wood: 600, steel: 5 } },
    ],
    effects: [
      { type: 'produce', resourceId: 'fur', perLevel: 0.5 },
      { type: 'produce', resourceId: 'meat', perLevel: 0.5 },
      { type: 'produce', resourceId: 'bone', perLevel: 0.3 },
      { type: 'produce', resourceId: 'scales', perLevel: 0.1 },
    ],
    workerSlots: 0,
    workerRole: '',
    dependencies: [],
    unlockCondition: { type: 'phase', target: 'hearth' },
  },
  {
    id: 'cart',
    name: 'cart',
    description: 'a rickety cart. goes places.',
    category: 'exploration',
    maxLevel: Infinity,
    costs: [
      { level: 1, resources: { wood: 30, fur: 5 } },
      { level: 2, resources: { wood: 80, iron: 10 } },
      { level: 3, resources: { wood: 150, steel: 5 } },
    ],
    effects: [
      { type: 'store', resourceId: 'carryCapacity', perLevel: 20 },
    ],
    workerSlots: 0,
    workerRole: '',
    dependencies: [{ buildingId: 'trap', level: 1 }],
    unlockCondition: { type: 'building', target: 'trap', value: 1 },
  },
  {
    id: 'hut',
    name: 'hut',
    description: 'a simple shelter. keeps the cold out. barely.',
    category: 'housing',
    maxLevel: Infinity,
    costs: [
      { level: 1, resources: { wood: 20 } },
      { level: 2, resources: { wood: 40 } },
      { level: 3, resources: { wood: 60, fur: 5 } },
      { level: 4, resources: { wood: 80, fur: 10 } },
      { level: 5, resources: { wood: 100, leather: 5 } },
      { level: 6, resources: { wood: 130, leather: 10 } },
      { level: 7, resources: { wood: 160, leather: 15, cloth: 5 } },
      { level: 8, resources: { wood: 200, cloth: 10 } },
      { level: 9, resources: { wood: 250, cloth: 15 } },
      { level: 10, resources: { wood: 300, iron: 5 } },
      { level: 11, resources: { wood: 350, iron: 10 } },
      { level: 12, resources: { wood: 400, iron: 15 } },
      { level: 13, resources: { wood: 450, iron: 20, coal: 5 } },
      { level: 14, resources: { wood: 500, iron: 25, coal: 10 } },
      { level: 15, resources: { wood: 550, steel: 5 } },
      { level: 16, resources: { wood: 600, steel: 10 } },
      { level: 17, resources: { wood: 650, steel: 15 } },
      { level: 18, resources: { wood: 700, steel: 20 } },
      { level: 19, resources: { wood: 750, steel: 25, alloy: 2 } },
      { level: 20, resources: { wood: 800, alloy: 5 } },
    ],
    effects: [
      { type: 'bonus', resourceId: 'workers', perLevel: 1 },
      { type: 'produce', resourceId: 'wood', perWorker: 1 },
      { type: 'produce', resourceId: 'herb', perWorker: 0.2 },
    ],
    workerSlots: 4,
    workerRole: 'gatherer',
    dependencies: [{ buildingId: 'trap', level: 1 }],
    unlockCondition: { type: 'building', target: 'trap', value: 1 },
  },
  {
    id: 'lodge',
    name: 'lodge',
    description: 'a large communal hall. warm light spills from the windows.',
    category: 'housing',
    maxLevel: Infinity,
    costs: [
      { level: 1, resources: { wood: 100, fur: 20 } },
      { level: 2, resources: { wood: 200, fur: 30, leather: 5 } },
      { level: 3, resources: { wood: 350, leather: 15, iron: 10 } },
      { level: 4, resources: { wood: 500, iron: 20, cloth: 10 } },
      { level: 5, resources: { wood: 700, steel: 25, alloy: 5 } },
    ],
    effects: [
      { type: 'bonus', resourceId: 'workers', perLevel: 4 },
    ],
    workerSlots: 0,
    workerRole: '',
    dependencies: [{ buildingId: 'hut', level: 2 }],
    unlockCondition: { type: 'building', target: 'hut', value: 2 },
  },
  {
    id: 'tradingPost',
    name: 'trading post',
    description: 'a place to barter. strangers come sometimes.',
    category: 'commerce',
    maxLevel: Infinity,
    costs: [
      { level: 1, resources: { wood: 80, fur: 15 } },
      { level: 2, resources: { wood: 200, leather: 20, iron: 10 } },
      { level: 3, resources: { wood: 400, steel: 15 } },
    ],
    effects: [
      { type: 'unlock', unlockId: 'trading' },
      { type: 'bonus', resourceId: 'tradeRate', perLevel: 0.1 },
    ],
    workerSlots: 0,
    workerRole: '',
    dependencies: [{ buildingId: 'hut', level: 1 }],
    unlockCondition: { type: 'building', target: 'hut', value: 1 },
  },
  {
    id: 'tannery',
    name: 'tannery',
    description: 'stretching racks and acid baths. the smell is terrible.',
    category: 'production',
    maxLevel: Infinity,
    costs: [
      { level: 1, resources: { wood: 50, fur: 20 } },
      { level: 2, resources: { wood: 100, fur: 30, iron: 5 } },
      { level: 3, resources: { wood: 180, leather: 15, iron: 10 } },
      { level: 4, resources: { wood: 280, iron: 20, coal: 10 } },
      { level: 5, resources: { wood: 400, steel: 10 } },
    ],
    effects: [
      { type: 'convert', inputResource: 'fur', outputResource: 'leather', conversionRate: 0.5, perWorker: 1 },
      { type: 'produce', resourceId: 'cloth', perWorker: 0.3 },
    ],
    workerSlots: 5,
    workerRole: 'tanner',
    dependencies: [{ buildingId: 'lodge', level: 1 }],
    unlockCondition: { type: 'building', target: 'lodge', value: 1 },
  },
  {
    id: 'smokehouse',
    name: 'smokehouse',
    description: 'thick smoke seeps through the walls. meat hangs in rows inside.',
    category: 'production',
    maxLevel: Infinity,
    costs: [
      { level: 1, resources: { wood: 60, meat: 10 } },
      { level: 2, resources: { wood: 120, leather: 10 } },
      { level: 3, resources: { wood: 200, iron: 10 } },
      { level: 4, resources: { wood: 300, iron: 20 } },
      { level: 5, resources: { wood: 400, steel: 5 } },
    ],
    effects: [
      { type: 'convert', inputResource: 'meat', outputResource: 'curedMeat', conversionRate: 0.8, perWorker: 1 },
    ],
    workerSlots: 3,
    workerRole: 'smoker',
    dependencies: [{ buildingId: 'trap', level: 2 }],
    unlockCondition: { type: 'building', target: 'trap', value: 2 },
  },
  {
    id: 'workshop',
    name: 'workshop',
    description: 'a cluttered workbench. tools hang from the walls.',
    category: 'production',
    maxLevel: Infinity,
    costs: [
      { level: 1, resources: { wood: 100, leather: 10 } },
      { level: 2, resources: { wood: 200, iron: 15 } },
      { level: 3, resources: { wood: 350, iron: 30, coal: 10 } },
      { level: 4, resources: { wood: 500, steel: 15 } },
      { level: 5, resources: { wood: 700, steel: 30, alloy: 5 } },
    ],
    effects: [
      { type: 'unlock', unlockId: 'advancedCrafting' },
    ],
    workerSlots: 0,
    workerRole: '',
    dependencies: [{ buildingId: 'lodge', level: 1 }],
    unlockCondition: { type: 'building', target: 'lodge', value: 1 },
  },
  {
    id: 'ironMine',
    name: 'iron mine',
    description: 'a dark shaft into the frozen earth. echoes carry far.',
    category: 'extraction',
    maxLevel: Infinity,
    costs: [
      { level: 1, resources: { wood: 150, leather: 15 } },
      { level: 2, resources: { wood: 250, iron: 20 } },
      { level: 3, resources: { wood: 400, iron: 40, coal: 10 } },
      { level: 4, resources: { wood: 600, steel: 10 } },
      { level: 5, resources: { wood: 800, steel: 25 } },
    ],
    effects: [
      { type: 'produce', resourceId: 'iron', perWorker: 0.5 },
    ],
    workerSlots: 6,
    workerRole: 'ironMiner',
    dependencies: [{ buildingId: 'workshop', level: 1 }],
    unlockCondition: { type: 'building', target: 'workshop', value: 1 },
  },
  {
    id: 'coalMine',
    name: 'coal mine',
    description: 'deeper than the iron mine. the air is thick and warm.',
    category: 'extraction',
    maxLevel: Infinity,
    costs: [
      { level: 1, resources: { wood: 150, leather: 15 } },
      { level: 2, resources: { wood: 250, iron: 20 } },
      { level: 3, resources: { wood: 400, iron: 40, coal: 15 } },
      { level: 4, resources: { wood: 600, steel: 10 } },
      { level: 5, resources: { wood: 800, steel: 25 } },
    ],
    effects: [
      { type: 'produce', resourceId: 'coal', perWorker: 0.5 },
      { type: 'produce', resourceId: 'sulphur', perWorker: 0.1 },
    ],
    workerSlots: 6,
    workerRole: 'coalMiner',
    dependencies: [{ buildingId: 'workshop', level: 1 }],
    unlockCondition: { type: 'building', target: 'workshop', value: 1 },
  },
  {
    id: 'steelworks',
    name: 'steelworks',
    description: 'the furnace roars day and night. sparks drift like fireflies.',
    category: 'production',
    maxLevel: Infinity,
    costs: [
      { level: 1, resources: { wood: 200, iron: 30, coal: 20 } },
      { level: 2, resources: { wood: 350, iron: 50, coal: 40 } },
      { level: 3, resources: { wood: 500, steel: 20, coal: 60 } },
      { level: 4, resources: { wood: 700, steel: 40, sulphur: 10 } },
      { level: 5, resources: { wood: 900, steel: 60, alloy: 5 } },
    ],
    effects: [
      { type: 'convert', inputResource: 'iron', outputResource: 'steel', conversionRate: 0.3, perWorker: 1 },
      { type: 'produce', resourceId: 'alloy', perLevel: 0.05 },
    ],
    workerSlots: 5,
    workerRole: 'steelworker',
    dependencies: [
      { buildingId: 'ironMine', level: 1 },
      { buildingId: 'coalMine', level: 1 },
    ],
    unlockCondition: { type: 'building', target: 'ironMine', value: 1 },
  },
  {
    id: 'armoury',
    name: 'armoury',
    description: 'blades gleam on the walls. the village has teeth now.',
    category: 'military',
    maxLevel: Infinity,
    costs: [
      { level: 1, resources: { wood: 300, steel: 20, leather: 20 } },
      { level: 2, resources: { wood: 500, steel: 40, alloy: 5 } },
      { level: 3, resources: { wood: 700, alloy: 15 } },
    ],
    effects: [
      { type: 'defense', amount: 5, perLevel: 5 },
      { type: 'unlock', unlockId: 'militaryCrafting' },
    ],
    workerSlots: 4,
    workerRole: 'armourer',
    dependencies: [{ buildingId: 'steelworks', level: 1 }],
    unlockCondition: { type: 'building', target: 'steelworks', value: 1 },
  },
  {
    id: 'storage',
    name: 'storage',
    description: 'a sturdy shed with thick walls. +10% to all resource caps per level.',
    category: 'utility',
    maxLevel: 20,
    costs: [
      { level: 1, resources: { wood: 30 } },
      { level: 2, resources: { wood: 60 } },
      { level: 3, resources: { wood: 100, fur: 5 } },
      { level: 4, resources: { wood: 150, fur: 10 } },
      { level: 5, resources: { wood: 220, leather: 10 } },
      { level: 6, resources: { wood: 300, leather: 15 } },
      { level: 7, resources: { wood: 400, iron: 10 } },
      { level: 8, resources: { wood: 520, iron: 20 } },
      { level: 9, resources: { wood: 660, steel: 10 } },
      { level: 10, resources: { wood: 820, steel: 20 } },
      { level: 11, resources: { wood: 1000, steel: 25 } },
      { level: 12, resources: { wood: 1200, steel: 30 } },
      { level: 13, resources: { wood: 1420, steel: 35 } },
      { level: 14, resources: { wood: 1660, steel: 40, alloy: 2 } },
      { level: 15, resources: { wood: 1920, alloy: 5 } },
      { level: 16, resources: { wood: 2200, alloy: 8 } },
      { level: 17, resources: { wood: 2500, alloy: 12 } },
      { level: 18, resources: { wood: 2820, alloy: 16 } },
      { level: 19, resources: { wood: 3160, alloy: 20 } },
      { level: 20, resources: { wood: 3520, alloy: 25 } },
    ],
    effects: [
      { type: 'store', resourceId: 'all_percent', perLevel: 10 },
    ],
    workerSlots: 0,
    workerRole: '',
    dependencies: [{ buildingId: 'hut', level: 1 }],
    unlockCondition: { type: 'building', target: 'hut', value: 1 },
  },
  {
    id: 'well',
    name: 'well',
    description: 'a deep shaft through frozen earth to the water below. essential for survival.',
    category: 'gathering',
    maxLevel: Infinity,
    costs: [
      { level: 1, resources: { wood: 40 } },
      { level: 2, resources: { wood: 80, fur: 5 } },
      { level: 3, resources: { wood: 130, leather: 5 } },
      { level: 4, resources: { wood: 200, iron: 5 } },
      { level: 5, resources: { wood: 280, iron: 10 } },
    ],
    effects: [
      { type: 'produce', resourceId: 'water', perLevel: 0.3 },
      { type: 'produce', resourceId: 'water', perWorker: 0.5 },
    ],
    workerSlots: 3,
    workerRole: 'waterCarrier',
    dependencies: [{ buildingId: 'hut', level: 1 }],
    unlockCondition: { type: 'building', target: 'hut', value: 1 },
  },
];

// ---------------------------------------------------------------------------
// Crafting recipes
// ---------------------------------------------------------------------------

const crafting: CraftRecipeDef[] = [
  {
    id: 'boneSpear',
    name: 'bone spear',
    description: 'a sharpened bone lashed to a pole. crude but deadly.',
    category: 'weapon',
    costs: { bone: 5, wood: 5 },
    result: {
      itemId: 'boneSpear',
      type: 'weapon',
      attack: 3,
      description: 'a sharpened bone lashed to a pole.',
      stackable: false,
    },
    unlockCondition: { type: 'resource', target: 'bone', value: 1 },
  },
  {
    id: 'furCloak',
    name: 'fur cloak',
    description: 'thick pelts stitched together. warm.',
    category: 'armor',
    costs: { fur: 10, cloth: 2 },
    result: {
      itemId: 'furCloak',
      type: 'armor',
      defense: 2,
      bonuses: { coldResist: 2 },
      description: 'a heavy cloak of animal pelts.',
      stackable: false,
    },
    unlockCondition: { type: 'resource', target: 'fur', value: 5 },
  },
  {
    id: 'leatherArmor',
    name: 'leather armor',
    description: 'boiled leather plates. flexible and tough.',
    category: 'armor',
    costs: { leather: 15, cloth: 5 },
    result: {
      itemId: 'leatherArmor',
      type: 'armor',
      defense: 4,
      bonuses: { coldResist: 1 },
      description: 'hardened leather plates laced together.',
      stackable: false,
    },
    buildingRequired: 'tannery',
    buildingLevel: 1,
    unlockCondition: { type: 'building', target: 'tannery', value: 1 },
  },
  {
    id: 'ironSword',
    name: 'iron sword',
    description: 'heavy blade. better than bone.',
    category: 'weapon',
    costs: { iron: 15, wood: 5, leather: 3 },
    result: {
      itemId: 'ironSword',
      type: 'weapon',
      attack: 6,
      description: 'a crude but heavy iron blade.',
      stackable: false,
    },
    buildingRequired: 'workshop',
    buildingLevel: 1,
    unlockCondition: { type: 'building', target: 'workshop', value: 1 },
  },
  {
    id: 'steelSword',
    name: 'steel sword',
    description: 'folded steel. light and sharp. sings when swung.',
    category: 'weapon',
    costs: { steel: 15, leather: 5, coal: 5 },
    result: {
      itemId: 'steelSword',
      type: 'weapon',
      attack: 10,
      description: 'a well-balanced blade of folded steel.',
      stackable: false,
    },
    buildingRequired: 'steelworks',
    buildingLevel: 1,
    unlockCondition: { type: 'building', target: 'steelworks', value: 1 },
  },
  {
    id: 'boneArrows',
    name: 'bone arrows',
    description: 'a bundle of sharpened bone-tipped shafts.',
    category: 'consumable',
    costs: { bone: 3, wood: 3 },
    result: {
      itemId: 'boneArrows',
      type: 'consumable',
      attack: 2,
      description: 'bone-tipped arrows. expendable.',
      stackable: true,
    },
    unlockCondition: { type: 'resource', target: 'bone', value: 1 },
  },
  {
    id: 'healingSalve',
    name: 'healing salve',
    description: 'a thick paste of herbs and fat. stings, then soothes.',
    category: 'consumable',
    costs: { herb: 3, fur: 1 },
    result: {
      itemId: 'healingSalve',
      type: 'consumable',
      bonuses: { heal: 20 },
      description: 'a foul-smelling paste that mends wounds.',
      stackable: true,
    },
    unlockCondition: { type: 'resource', target: 'herb', value: 1 },
  },
  {
    id: 'compass',
    name: 'compass',
    description: 'a magnetised needle floating in oil. points to something.',
    category: 'tool',
    costs: { iron: 10, wood: 5, cloth: 3 },
    result: {
      itemId: 'compass',
      type: 'accessory',
      bonuses: { mapReveal: 3 },
      description: 'the needle trembles. it knows the way.',
      stackable: false,
    },
    buildingRequired: 'workshop',
    buildingLevel: 1,
    unlockCondition: { type: 'building', target: 'workshop', value: 1 },
  },
  {
    id: 'waterFlask',
    name: 'water flask',
    description: 'a leather flask. sealed with pitch.',
    category: 'accessory',
    costs: { leather: 5, wood: 2 },
    result: {
      itemId: 'waterFlask',
      type: 'accessory',
      bonuses: { waterCapacity: 10 },
      description: 'carries water for the road.',
      stackable: false,
    },
    buildingRequired: 'tannery',
    buildingLevel: 1,
    unlockCondition: { type: 'building', target: 'tannery', value: 1 },
  },
  {
    id: 'rucksack',
    name: 'rucksack',
    description: 'a sturdy pack. carries more than pockets.',
    category: 'accessory',
    costs: { leather: 10, cloth: 8 },
    result: {
      itemId: 'rucksack',
      type: 'accessory',
      bonuses: { carryCapacity: 15 },
      description: 'a large pack with many pockets.',
      stackable: false,
    },
    buildingRequired: 'tannery',
    buildingLevel: 1,
    unlockCondition: { type: 'building', target: 'tannery', value: 1 },
  },
  {
    id: 'ironFlask',
    name: 'iron flask',
    description: 'a reinforced metal canteen. holds much more than leather.',
    category: 'accessory',
    costs: { iron: 10, leather: 5 },
    result: {
      itemId: 'ironFlask',
      type: 'accessory',
      bonuses: { waterCapacity: 25 },
      description: 'a heavy iron flask. sealed tight.',
      stackable: false,
    },
    buildingRequired: 'workshop',
    buildingLevel: 1,
    unlockCondition: { type: 'building', target: 'workshop', value: 1 },
  },
  {
    id: 'steelCanteen',
    name: 'steel canteen',
    description: 'insulated steel. keeps water fresh for days.',
    category: 'accessory',
    costs: { steel: 8, leather: 5, cloth: 3 },
    result: {
      itemId: 'steelCanteen',
      type: 'accessory',
      bonuses: { waterCapacity: 50 },
      description: 'a polished steel canteen with a cork seal.',
      stackable: false,
    },
    buildingRequired: 'steelworks',
    buildingLevel: 1,
    unlockCondition: { type: 'building', target: 'steelworks', value: 1 },
  },
  {
    id: 'largeRucksack',
    name: 'large rucksack',
    description: 'reinforced with iron frames. carries twice the load.',
    category: 'accessory',
    costs: { leather: 15, iron: 8, cloth: 5 },
    result: {
      itemId: 'largeRucksack',
      type: 'accessory',
      bonuses: { carryCapacity: 30, foodCapacity: 15 },
      description: 'a huge pack. strains the shoulders but holds everything.',
      stackable: false,
    },
    buildingRequired: 'workshop',
    buildingLevel: 1,
    unlockCondition: { type: 'building', target: 'workshop', value: 1 },
  },
  {
    id: 'expeditionPack',
    name: 'expedition pack',
    description: 'steel-framed. compartments for everything. built for the long haul.',
    category: 'accessory',
    costs: { steel: 10, leather: 10, cloth: 8 },
    result: {
      itemId: 'expeditionPack',
      type: 'accessory',
      bonuses: { carryCapacity: 50, foodCapacity: 30 },
      description: 'a masterwork pack. pockets within pockets.',
      stackable: false,
    },
    buildingRequired: 'steelworks',
    buildingLevel: 1,
    unlockCondition: { type: 'building', target: 'steelworks', value: 1 },
  },
  {
    id: 'ironArmor',
    name: 'iron armor',
    description: 'plates of hammered iron. heavy but dependable.',
    category: 'armor',
    costs: { iron: 25, leather: 10, cloth: 5 },
    result: {
      itemId: 'ironArmor',
      type: 'armor',
      defense: 7,
      bonuses: { coldResist: 2 },
      description: 'crude iron plates strapped over leather.',
      stackable: false,
    },
    buildingRequired: 'workshop',
    buildingLevel: 2,
    unlockCondition: { type: 'building', target: 'workshop', value: 2 },
  },
  {
    id: 'steelArmor',
    name: 'steel armor',
    description: 'interlocking steel plates. glints in the firelight.',
    category: 'armor',
    costs: { steel: 25, leather: 10, coal: 10 },
    result: {
      itemId: 'steelArmor',
      type: 'armor',
      defense: 12,
      bonuses: { coldResist: 3 },
      description: 'fitted steel plates. almost comfortable.',
      stackable: false,
    },
    buildingRequired: 'armoury',
    buildingLevel: 1,
    unlockCondition: { type: 'building', target: 'armoury', value: 1 },
  },
  {
    id: 'alloySword',
    name: 'alloy sword',
    description: 'a blade of old-world metal. impossibly light. the edge never dulls.',
    category: 'weapon',
    costs: { alloy: 15, steel: 10, sulphur: 5 },
    result: {
      itemId: 'alloySword',
      type: 'weapon',
      attack: 16,
      description: 'old-world metal sings with each cut. the edge never dulls.',
      stackable: false,
    },
    buildingRequired: 'armoury',
    buildingLevel: 2,
    unlockCondition: { type: 'building', target: 'armoury', value: 2 },
  },
  {
    id: 'alloyArmor',
    name: 'alloy armor',
    description: 'plates of old-world metal fitted together. light as cloth, hard as anything.',
    category: 'armor',
    costs: { alloy: 20, steel: 15, leather: 10 },
    result: {
      itemId: 'alloyArmor',
      type: 'armor',
      defense: 18,
      bonuses: { coldResist: 5 },
      description: 'old-world armor. moves like a second skin.',
      stackable: false,
    },
    buildingRequired: 'armoury',
    buildingLevel: 3,
    unlockCondition: { type: 'building', target: 'armoury', value: 3 },
  },
  {
    id: 'vesselHull',
    name: 'vessel hull',
    description: 'the outer shell. curved metal plates welded together.',
    category: 'vessel',
    costs: { alloy: 25, steel: 30, iron: 20 },
    result: {
      itemId: 'vesselHull',
      type: 'material',
      description: 'the skeleton of something meant to fly.',
      stackable: false,
    },
    buildingRequired: 'armoury',
    buildingLevel: 2,
    unlockCondition: { type: 'quest', target: 'mainDiscover', value: 3 },
  },
  {
    id: 'vesselEngine',
    name: 'vessel engine',
    description: 'a compact engine. old-world design. rebuilt from blueprints.',
    category: 'vessel',
    costs: { alloy: 20, steel: 20, coal: 30, sulphur: 15 },
    result: {
      itemId: 'vesselEngine',
      type: 'material',
      description: 'the heart of the vessel. it hums when touched.',
      stackable: false,
    },
    buildingRequired: 'armoury',
    buildingLevel: 2,
    unlockCondition: { type: 'quest', target: 'mainDiscover', value: 4 },
  },
  {
    id: 'vesselNav',
    name: 'navigation module',
    description: 'circuits and glass. the cartographer helped design it.',
    category: 'vessel',
    costs: { alloy: 15, iron: 10, scales: 10 },
    result: {
      itemId: 'vesselNav',
      type: 'material',
      description: 'a navigation module. it knows where to go.',
      stackable: false,
    },
    buildingRequired: 'workshop',
    buildingLevel: 3,
    unlockCondition: { type: 'quest', target: 'mainDiscover', value: 4 },
  },
];

// ---------------------------------------------------------------------------
// Phase configuration
// ---------------------------------------------------------------------------

const phases: Record<Phase, PhaseConfig> = {
  spark: {
    trigger: 'true',
    unlocks: ['stoke', 'gather'],
    text: 'the room is dark. the fire is almost dead.',
  },
  hearth: {
    trigger: 'stokeCount >= 15',
    unlocks: ['build', 'trap', 'hut', 'cart'],
    text: 'the fire burns steady now. the room is warm. there is a knock at the door.',
  },
  settlement: {
    trigger: 'building.hut.level >= 2 && resource.fur > 0',
    unlocks: ['lodge', 'tradingPost', 'tannery', 'smokehouse', 'workers'],
    text: 'smoke rises from more than one chimney now. a village is forming in the snow.',
  },
  questWeb: {
    trigger: 'quest.mainDiscover.active == true && building.workshop.level >= 1',
    unlocks: ['workshop', 'ironMine', 'coalMine', 'advancedCrafting'],
    text: 'the builder speaks of old machines. there is purpose now. something to work toward.',
  },
  wild: {
    trigger: 'building.cart.level >= 1 && crafted.includes("compass")',
    unlocks: ['exploration', 'map', 'steelworks', 'armoury'],
    text: 'the compass needle trembles. beyond the firelight, the wasteland waits.',
  },
  reckoning: {
    trigger: 'flag.mapExplored70 == true',
    unlocks: ['vesselCrafting', 'bossArena'],
    text: 'the map is nearly complete. at the edge, something stirs. something that was waiting.',
  },
  departure: {
    trigger: 'flag.bossDefeated == true',
    unlocks: ['vessel', 'departure'],
    text: 'the beast is dead. the way is clear. it is time to leave this place.',
  },
};

// ---------------------------------------------------------------------------
// Environmental pressure — Cold
// ---------------------------------------------------------------------------

const environmentalPressure = {
  id: 'cold',
  name: 'cold',
  description: 'the cold seeps through the walls. the fire is the only thing between life and death.',
  meter: { min: 0, max: 100, startValue: 50, dangerThreshold: 15 },
  decayRate: 0.15,
  damageRate: 0.3,
  mitigators: [
    { type: 'building' as const, id: 'hut', effect: 0.05 },
    { type: 'building' as const, id: 'lodge', effect: 0.15 },
    { type: 'resource' as const, id: 'wood', effect: 0.2 },
    { type: 'gear' as const, id: 'furCloak', effect: 0.1 },
  ],
};

// ---------------------------------------------------------------------------
// Boss — The Raider King
// ---------------------------------------------------------------------------

const boss = {
  id: 'raiderKing',
  name: 'the raider king',
  description: 'a massive figure clad in scrap metal and bone. the wasteland bent to his will. now he bends it toward you.',
  phases: [
    {
      health: 120,
      attack: 8,
      defense: 6,
      speed: 3,
      description: 'the raider king circles slowly. testing. his warband watches from the edges.',
    },
    {
      health: 100,
      attack: 12,
      defense: 4,
      speed: 5,
      description: 'blood runs down his face. he throws his shield aside and charges with both blades.',
      specialMechanic: 'dualWield',
    },
    {
      health: 60,
      attack: 16,
      defense: 2,
      speed: 7,
      description: 'he is screaming now. wordless rage. each blow shakes the ground.',
      specialMechanic: 'berserk',
    },
  ],
  loot: {
    alloy: 20,
    steel: 15,
    iron: 25,
    sulphur: 10,
  },
  defeatCondition: 'boss.raiderKing.health <= 0',
};

// ---------------------------------------------------------------------------
// Vessel — The Way Out
// ---------------------------------------------------------------------------

const vessel: { id: string; name: string; stages: { id: string; name: string; costs: Record<string, number>; description: string }[] } = {
  id: 'vessel',
  name: 'the vessel',
  stages: [
    {
      id: 'hull',
      name: 'hull assembly',
      costs: { alloy: 25, steel: 30, iron: 20 },
      description: 'the frame takes shape. curved metal plates welded into the skeleton of something meant to fly.',
    },
    {
      id: 'engine',
      name: 'engine installation',
      costs: { alloy: 20, steel: 20, coal: 30, sulphur: 15 },
      description: 'the engine sits in the belly of the vessel. it hums when connected. a heartbeat.',
    },
    {
      id: 'nav',
      name: 'navigation systems',
      costs: { alloy: 15, iron: 10, scales: 10 },
      description: 'the navigation module clicks into place. the screen flickers on. coordinates appear.',
    },
    {
      id: 'supplies',
      name: 'provision loading',
      costs: { curedMeat: 50, water: 30, wood: 100, cloth: 20 },
      description: 'food and water stacked in the hold. enough for the journey. maybe.',
    },
    {
      id: 'launch',
      name: 'launch preparation',
      costs: { sulphur: 20, coal: 40, alloy: 10 },
      description: 'the fuel lines are connected. the vessel shudders. ready.',
    },
  ],
};

// ---------------------------------------------------------------------------
// Exits
// ---------------------------------------------------------------------------

const exits = {
  standard: {
    id: 'vesselDeparture',
    name: 'the vessel',
    description: 'the vessel waits on the frozen field. the engine idles. there is room for one.',
    conditions: [
      { type: 'flag' as const, target: 'bossDefeated', value: true },
      { type: 'item' as const, target: 'vesselHull', value: 1 },
      { type: 'item' as const, target: 'vesselEngine', value: 1 },
      { type: 'item' as const, target: 'vesselNav', value: 1 },
    ],
    narrative: [
      'the vessel hums on the frozen field.',
      'the villagers watch in silence.',
      'you climb inside. the hatch seals.',
      'the engine roars. the ground falls away.',
      'the dark room shrinks below. then the village. then the wasteland.',
      'then there is only sky.',
    ],
  },
  hidden: [
    {
      id: 'hermitPath',
      name: 'the hermit\'s path',
      description: 'a passage beneath the ruins. the hermit said it leads somewhere else. somewhere before.',
      conditions: [
        { type: 'quest_complete' as const, target: 'hermitMemory', value: true },
        { type: 'npc_relationship' as const, target: 'hermit', value: 8 },
        { type: 'flag' as const, target: 'hermitPathRevealed', value: true },
      ],
      narrative: [
        'the passage slopes down into the earth.',
        'the walls are smooth. old-world construction.',
        'the hermit waits at the bottom. he nods.',
        '"i remember now," he says. "i remember all of it."',
        'he touches the wall. a door opens.',
        'warm light spills through.',
        'a bright room.',
      ],
    },
    {
      id: 'frozenLakeDescend',
      name: 'beneath the ice',
      description: 'the frozen lake hides something beneath. the ice is clear enough to see down into the dark.',
      conditions: [
        { type: 'map_explored' as const, target: 'frozenLake', value: true },
        { type: 'item' as const, target: 'alloySword', value: 1 },
        { type: 'flag' as const, target: 'lakeSecretFound', value: true },
      ],
      narrative: [
        'the ice cracks under the alloy blade.',
        'water dark as ink. but there is no cold.',
        'you sink through the lake like falling through a dream.',
        'at the bottom, light. a machine. still running after all this time.',
        'the screen reads: CHAPTER 2 — LOADING.',
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Departure narratives
// ---------------------------------------------------------------------------

const departure = {
  standardNarrative: [
    'the vessel climbs through grey cloud.',
    'below, the fire in the dark room still burns.',
    'the stranger tends it now. the builder adds a room.',
    'the village will survive. you made sure of that.',
    'but the world is wider than one frozen valley.',
    'the compass needle spins. then steadies.',
    'it points forward.',
  ],
  hiddenNarrative: [
    'the door closes behind you.',
    'the light is warm. not fire-warm. something else.',
    'the hermit was right. there was something before the cold.',
    'something bright.',
    'you step through.',
  ],
};

// ---------------------------------------------------------------------------
// Checkpoints
// ---------------------------------------------------------------------------

const checkpoints = [
  { id: 'cp_spark', trigger: 'phase == "spark"', label: 'the dark room' },
  { id: 'cp_hearth', trigger: 'phase == "hearth"', label: 'the fire burns' },
  { id: 'cp_settlement', trigger: 'phase == "settlement"', label: 'a village in the snow' },
  { id: 'cp_questWeb', trigger: 'phase == "questWeb"', label: 'purpose' },
  { id: 'cp_wild', trigger: 'phase == "wild"', label: 'the wasteland' },
  { id: 'cp_reckoning', trigger: 'phase == "reckoning"', label: 'the reckoning' },
  { id: 'cp_departure', trigger: 'phase == "departure"', label: 'departure' },
  { id: 'cp_firstHut', trigger: 'building.hut.level >= 1', label: 'first shelter' },
  { id: 'cp_firstIron', trigger: 'resource.iron > 0', label: 'iron age' },
  { id: 'cp_firstSteel', trigger: 'resource.steel > 0', label: 'steel age' },
  { id: 'cp_bossDefeated', trigger: 'flag.bossDefeated == true', label: 'the king falls' },
];

// ---------------------------------------------------------------------------
// Assemble the full chapter config
// ---------------------------------------------------------------------------

export const chapter01Config: ChapterConfig = {
  id: 'chapter01-dark-room',
  name: 'a dark room',
  chapterNumber: 1,

  theme: {
    primary: '#D4A04A',
    accent: '#C0392B',
    bg: '#0A0A0A',
    font: '"IBM Plex Mono", "Courier New", monospace',
  },

  phases,

  stokeAction: {
    name: 'stoke the fire',
    description: 'feed the flames. push back the dark.',
    resourceCost: {},
    cooldown: 7,
    effect: 'resource.wood + 5',
    upgradesAvailable: true,
  },

  resources,
  buildings,
  crafting,
  npcs,
  map: mapConfig,
  events,
  boss,
  vessel,
  departure,
  exits,
  environmentalPressure,
  newMechanic: null,

  startingResources: { wood: 5 },
  startingHealth: 100,
  maxHealth: 100,

  checkpoints,
};
