// Chapter 01 — Map Configuration
// 40x40 frozen wasteland with forests, swamps, caves, ruins, and the old city

import { MapConfig, TerrainDef, POIDef, EnemyDef, HiddenAreaDef } from '@/types/chapter';

// ---------------------------------------------------------------------------
// Terrain types
// ---------------------------------------------------------------------------

const terrainTypes: TerrainDef[] = [
  {
    id: 'forest',
    name: 'forest',
    symbol: 'T',
    color: '#2D5A27',
    passable: true,
    encounterRate: 0.15,
  },
  {
    id: 'swamp',
    name: 'swamp',
    symbol: '~',
    color: '#4A6741',
    passable: true,
    encounterRate: 0.25,
  },
  {
    id: 'cave',
    name: 'cave',
    symbol: 'C',
    color: '#3D3D3D',
    passable: true,
    hazard: { damagePerTick: 1, type: 'darkness', resistGear: 'torch' },
    encounterRate: 0.35,
  },
  {
    id: 'ruins',
    name: 'ruins',
    symbol: '#',
    color: '#8B7355',
    passable: true,
    encounterRate: 0.2,
  },
  {
    id: 'battlefield',
    name: 'battlefield',
    symbol: 'X',
    color: '#6B3A3A',
    passable: true,
    encounterRate: 0.2,
  },
  {
    id: 'city',
    name: 'city',
    symbol: 'U',
    color: '#5A5A6E',
    passable: true,
    encounterRate: 0.3,
  },
  {
    id: 'mountain',
    name: 'mountain',
    symbol: 'M',
    color: '#7A7A7A',
    passable: true,
    hazard: { damagePerTick: 2, type: 'cold', resistGear: 'furCloak' },
    encounterRate: 0.1,
  },
  {
    id: 'frozenLake',
    name: 'frozen lake',
    symbol: '=',
    color: '#6B8FA3',
    passable: true,
    hazard: { damagePerTick: 3, type: 'thinIce', resistGear: 'rucksack' },
    encounterRate: 0.05,
  },
  {
    id: 'village',
    name: 'village',
    symbol: 'V',
    color: '#D4A04A',
    passable: true,
    encounterRate: 0,
  },
  {
    id: 'snow',
    name: 'open snow',
    symbol: '.',
    color: '#C8C8D0',
    passable: true,
    encounterRate: 0.08,
  },
  {
    id: 'deepSnow',
    name: 'deep snow',
    symbol: ':',
    color: '#E8E8F0',
    passable: true,
    hazard: { damagePerTick: 1, type: 'cold', resistGear: 'furCloak' },
    encounterRate: 0.05,
  },
  {
    id: 'cliff',
    name: 'cliff',
    symbol: '|',
    color: '#555555',
    passable: false,
    encounterRate: 0,
  },
];

// ---------------------------------------------------------------------------
// Points of Interest (30+)
// ---------------------------------------------------------------------------

const pointsOfInterest: POIDef[] = [
  // === Village (center) ===
  {
    id: 'poi_village',
    name: 'the village',
    description: 'home. the fire burns here.',
    type: 'outpost',
    position: { x: 20, y: 20, z: 0 },
    discoveryText: 'the village. smoke rises from the chimneys. the fire burns.',
    hidden: false,
  },

  // === Nearby (within 5 tiles) ===
  {
    id: 'poi_frozenStream',
    name: 'the frozen stream',
    description: 'a narrow stream locked in ice. water moves beneath.',
    type: 'landmark',
    position: { x: 22, y: 18, z: 0 },
    discoveryText: 'a stream, frozen solid. beneath the ice, dark water still flows.',
    loot: { water: 50 },
    hidden: false,
  },
  {
    id: 'poi_oldCabin',
    name: 'the old cabin',
    description: 'a collapsed cabin. someone lived here before.',
    type: 'cache',
    position: { x: 18, y: 17, z: 0 },
    discoveryText: 'a cabin, half-crushed by a fallen tree. inside, supplies remain.',
    loot: { wood: 200, cloth: 50, fur: 30 },
    hidden: false,
  },
  {
    id: 'poi_huntersBlind',
    name: 'the hunter\'s blind',
    description: 'a concealed platform in the trees. good vantage point.',
    type: 'landmark',
    position: { x: 23, y: 22, z: 0 },
    discoveryText: 'a hunter\'s blind, built into the branches. the view is good. the forest spreads in all directions.',
    loot: { bone: 50, boneArrows: 30 },
    hidden: false,
  },

  // === Medium distance (5-12 tiles) ===
  {
    id: 'poi_wolfDen',
    name: 'the wolf den',
    description: 'a cave mouth. bones scattered at the entrance.',
    type: 'dungeon',
    position: { x: 14, y: 15, z: 0 },
    discoveryText: 'a dark cave. the smell of animal. bones crunch underfoot. this is a wolf den.',
    loot: { fur: 100, teeth: 80, meat: 50, bone: 100 },
    hidden: false,
  },
  {
    id: 'poi_abandonedFarm',
    name: 'the abandoned farm',
    description: 'fields of dead crops under snow. a barn still stands.',
    type: 'cache',
    position: { x: 27, y: 18, z: 0 },
    discoveryText: 'a farm. the fields are white and dead. but the barn holds supplies — preserved food, old tools.',
    loot: { wood: 150, curedMeat: 80, cloth: 50, herb: 60 },
    hidden: false,
  },
  {
    id: 'poi_traderCamp',
    name: 'the trader\'s camp',
    description: 'a semi-permanent camp. someone does business here.',
    type: 'outpost',
    position: { x: 15, y: 25, z: 0 },
    discoveryText: 'a trader\'s camp. tents and a fire ring. goods stacked on sleds. "trade?" says a voice from inside.',
    loot: { iron: 50, leather: 80, cloth: 100 },
    hidden: false,
  },
  {
    id: 'poi_oldBridge',
    name: 'the old bridge',
    description: 'a stone bridge over a frozen gorge. old-world construction.',
    type: 'landmark',
    position: { x: 25, y: 14, z: 0 },
    discoveryText: 'a bridge. stone and iron. it has survived everything. the gorge below is deep and dark.',
    hidden: false,
  },
  {
    id: 'poi_herbGarden',
    name: 'the wild garden',
    description: 'sheltered in a hollow, plants still grow. green in a white world.',
    type: 'cache',
    position: { x: 17, y: 23, z: 0 },
    discoveryText: 'a hollow sheltered from the wind. plants grow here — herbs, roots. a pocket of life in the frozen waste.',
    loot: { herb: 150 },
    hidden: false,
  },
  {
    id: 'poi_watchTower',
    name: 'the watch tower',
    description: 'a wooden tower on a hill. the view extends for miles.',
    type: 'landmark',
    position: { x: 26, y: 25, z: 0 },
    discoveryText: 'a watch tower. the steps creak but hold. from the top, the world stretches out — white and grey and endless.',
    hidden: false,
  },

  // === Far (12-18 tiles) ===
  {
    id: 'poi_hermitRuins',
    name: 'the broken school',
    description: 'ruins of a school. walls half-standing. someone lives here.',
    type: 'quest',
    position: { x: 10, y: 12, z: 0 },
    discoveryText: 'a school. crumbling walls and a collapsed roof. among the rubble, an old man sits perfectly still.',
    questTrigger: 'hermitMemory',
    hidden: true,
    revealCondition: 'flag.cartographerAccepted == true || exploredCount >= 200',
  },
  {
    id: 'poi_oldBunker',
    name: 'the old bunker',
    description: 'a steel door in a hillside. old-world markings. "AUTHORIZED PERSONNEL ONLY."',
    type: 'dungeon',
    position: { x: 8, y: 28, z: 0 },
    discoveryText: 'a bunker. the steel door is ajar. cold air flows from inside, but different cold — stale, recycled. old-world cold.',
    loot: { iron: 200, alloy: 50, cloth: 100, steel: 80 },
    questTrigger: 'mainDiscover',
    hidden: true,
    revealCondition: 'quest.mainDiscover.step >= 3 || flag.undergroundMapRevealed == true',
  },
  {
    id: 'poi_raiderOutpost',
    name: 'the raider outpost',
    description: 'a fortified camp. sharpened logs and fire pits. raiders.',
    type: 'dungeon',
    position: { x: 30, y: 10, z: 0 },
    discoveryText: 'a raider camp. walls of sharpened logs. fire pits. the smell of smoke and blood.',
    loot: { iron: 100, leather: 150, meat: 100, bone: 80 },
    questTrigger: 'scoutPatrol',
    hidden: false,
  },
  {
    id: 'poi_abandonedFactory',
    name: 'the abandoned factory',
    description: 'a massive building. machines rusting inside. the assembly line is frozen.',
    type: 'cache',
    position: { x: 32, y: 22, z: 0 },
    discoveryText: 'a factory. the machines are silent. rust eats the gears. but in the store rooms, raw materials remain.',
    loot: { iron: 250, coal: 150, steel: 50, cloth: 80 },
    hidden: false,
  },
  {
    id: 'poi_radioTower',
    name: 'the radio tower',
    description: 'a tall metal tower. the antenna is broken but the structure stands.',
    type: 'landmark',
    position: { x: 12, y: 30, z: 0 },
    discoveryText: 'a radio tower. the red light at the top still blinks. slow. steady. who is it signaling?',
    loot: { iron: 80, alloy: 30 },
    hidden: false,
  },
  {
    id: 'poi_frozenLakeCamp',
    name: 'the ice fisher\'s camp',
    description: 'a small camp on the frozen lake. a hole cut in the ice.',
    type: 'cache',
    position: { x: 28, y: 32, z: 0 },
    discoveryText: 'a camp on the ice. someone cut a hole and fished here. the catch is frozen but preserved.',
    loot: { meat: 120, bone: 60, water: 80 },
    hidden: false,
  },
  {
    id: 'poi_scoutSurvivor1',
    name: 'the eastern camp',
    description: 'a makeshift camp in the ruins. someone survived here.',
    type: 'quest',
    position: { x: 30, y: 15, z: 0 },
    discoveryText: 'a camp tucked into the ruins. a fire pit, cold. marks on the wall — tally marks. someone counting days.',
    questTrigger: 'scoutPatrol',
    hidden: true,
    revealCondition: 'flag.patrolSearchStarted == true',
  },
  {
    id: 'poi_scoutSurvivor2',
    name: 'the northern hideout',
    description: 'a shelter in the northern forest. well-hidden.',
    type: 'quest',
    position: { x: 18, y: 8, z: 0 },
    discoveryText: 'a shelter built into a fallen tree. military gear inside. someone trained made this.',
    questTrigger: 'scoutPatrol',
    hidden: true,
    revealCondition: 'flag.patrolSearchStarted == true',
  },

  // === Distant (18+ tiles) ===
  {
    id: 'poi_theCity',
    name: 'the shattered city',
    description: 'towers of glass and steel. all broken. the raider king rules from here.',
    type: 'dungeon',
    position: { x: 35, y: 5, z: 0 },
    discoveryText: 'the city. towers like broken teeth against the sky. fires burn in the lower levels. this is the raider king\'s domain.',
    loot: { alloy: 100, steel: 150, iron: 200, sulphur: 80 },
    hidden: false,
  },
  {
    id: 'poi_bossArena',
    name: 'the king\'s court',
    description: 'a cleared plaza in the city center. the raider king\'s throne — a car seat on a pile of rubble.',
    type: 'boss',
    position: { x: 36, y: 4, z: 0 },
    discoveryText: 'the king\'s court. a clearing in the ruins. a throne of junk. he waits.',
    hidden: true,
    revealCondition: 'flag.mapExplored70 == true && flag.raiderKingKnown == true',
  },
  {
    id: 'poi_frozenLake',
    name: 'the great frozen lake',
    description: 'a vast lake. the ice is clear as glass. something glows beneath.',
    type: 'landmark',
    position: { x: 5, y: 35, z: 0 },
    discoveryText: 'a frozen lake stretching to the horizon. the ice is clear. far below, a light pulses. blue. steady.',
    hidden: false,
  },
  {
    id: 'poi_lakeSecret',
    name: 'the light beneath',
    description: 'below the ice, a machine. still running. still waiting.',
    type: 'exit',
    position: { x: 5, y: 35, z: -1 },
    discoveryText: 'the ice gives way. below, warm water. and deeper still, a chamber. a screen flickers on.',
    hidden: true,
    revealCondition: 'crafted.includes("alloySword") && flag.frozenLakeVisited == true',
  },
  {
    id: 'poi_crashSite',
    name: 'the crash site',
    description: 'something fell from the sky. a long time ago. the crater is frozen.',
    type: 'cache',
    position: { x: 4, y: 8, z: 0 },
    discoveryText: 'a crater. at the center, twisted metal. old-world design — no, older than old-world. something foreign.',
    loot: { alloy: 120, scales: 80 },
    hidden: false,
  },
  {
    id: 'poi_graveyard',
    name: 'the old cemetery',
    description: 'rows of headstones under snow. names and dates from the old world.',
    type: 'landmark',
    position: { x: 15, y: 5, z: 0 },
    discoveryText: 'a cemetery. hundreds of graves. the stones are worn but legible. names. dates. "beloved." the last dates are all the same year.',
    hidden: false,
  },
  {
    id: 'poi_railyard',
    name: 'the dead railyard',
    description: 'train cars rusting on tracks that go nowhere. a graveyard of machines.',
    type: 'cache',
    position: { x: 33, y: 30, z: 0 },
    discoveryText: 'a railyard. engines and cars, frozen in place. the metal is good. the coal cars are still half-full.',
    loot: { iron: 300, coal: 250, steel: 80 },
    hidden: false,
  },
  {
    id: 'poi_hospital',
    name: 'the old hospital',
    description: 'a crumbling building with a faded red cross. medical supplies may remain.',
    type: 'cache',
    position: { x: 8, y: 15, z: 0 },
    discoveryText: 'a hospital. the halls are dark and cold. but the pharmacy — locked, sealed. supplies preserved inside.',
    loot: { herb: 200, cloth: 150 },
    hidden: false,
  },
  {
    id: 'poi_undergroundEntrance',
    name: 'the tunnel entrance',
    description: 'a hole in the ground. metal walls visible below. old-world tunnels.',
    type: 'dungeon',
    position: { x: 10, y: 32, z: 0 },
    discoveryText: 'a tunnel entrance. metal walls, still smooth. the old world built deep. the air below is warm and stale.',
    loot: { alloy: 80, iron: 120, sulphur: 60 },
    hidden: true,
    revealCondition: 'flag.undergroundMapRevealed == true',
  },
  {
    id: 'poi_frozenRiver',
    name: 'the frozen river crossing',
    description: 'the river is wide and frozen solid. tracks cross it.',
    type: 'landmark',
    position: { x: 25, y: 8, z: 0 },
    discoveryText: 'a frozen river. wide enough to need a bridge, but the ice holds. tracks in the snow cross from both sides.',
    hidden: false,
  },
  {
    id: 'poi_militaryBase',
    name: 'the abandoned base',
    description: 'a military compound. barracks and vehicles, all frozen. the flag is gone.',
    type: 'cache',
    position: { x: 5, y: 20, z: 0 },
    discoveryText: 'a military base. the gate hangs open. barracks, motor pool, armory. the armory door is locked. but not forever.',
    loot: { iron: 150, steel: 100, leather: 120, cloth: 80 },
    hidden: false,
  },
  {
    id: 'poi_strangeMonolith',
    name: 'the monolith',
    description: 'a tall black stone. perfectly smooth. no snow sticks to it.',
    type: 'landmark',
    position: { x: 20, y: 3, z: 0 },
    discoveryText: 'a monolith. black stone, tall as three people. the surface is warm. no snow touches it. symbols carved into the base, too worn to read.',
    hidden: false,
  },
  {
    id: 'poi_coalDeposit',
    name: 'the surface coal deposit',
    description: 'black rock exposed by a landslide. coal. a lot of it.',
    type: 'cache',
    position: { x: 12, y: 22, z: 0 },
    discoveryText: 'a hillside split open. black veins of coal exposed to the air. easy pickings.',
    loot: { coal: 300 },
    hidden: false,
  },
  {
    id: 'poi_sulphurVent',
    name: 'the yellow spring',
    description: 'a hot spring rimmed with yellow crystal. the air smells of rotten eggs.',
    type: 'cache',
    position: { x: 35, y: 35, z: 0 },
    discoveryText: 'a hot spring. warm water bubbles up from below. yellow crystals crust the rim. sulphur. the smell is terrible but the resource is precious.',
    loot: { sulphur: 150, water: 100 },
    hidden: false,
  },
  {
    id: 'poi_hermitPath',
    name: 'the hidden passage',
    description: 'beneath the ruins, a door. old-world metal. the hermit\'s secret.',
    type: 'exit',
    position: { x: 10, y: 12, z: -1 },
    discoveryText: 'the passage opens. warm light spills up from below. the hermit nods. "go on," he says.',
    hidden: true,
    revealCondition: 'flag.hermitPathRevealed == true',
  },
  {
    id: 'poi_vesselField',
    name: 'the launch field',
    description: 'a flat clearing east of the village. packed snow. room for something large.',
    type: 'landmark',
    position: { x: 25, y: 20, z: 0 },
    discoveryText: 'a flat field of packed snow. the ground is level. firm. the builder looks at it and nods. "this will do."',
    hidden: true,
    revealCondition: 'flag.vesselBlueprintRevealed == true',
  },
];

// ---------------------------------------------------------------------------
// Enemies (8 types scaling with distance)
// ---------------------------------------------------------------------------

const enemies: EnemyDef[] = [
  {
    id: 'feralDog',
    name: 'feral dog',
    description: 'a starving dog. ribs showing. teeth bared. it was someone\'s pet once.',
    health: 15,
    attack: 3,
    defense: 1,
    speed: 5,
    terrain: ['forest', 'snow', 'ruins'],
    minDistance: 2,
    loot: [
      { itemId: 'fur', chance: 0.6, quantity: 2 },
      { itemId: 'meat', chance: 0.5, quantity: 2 },
      { itemId: 'teeth', chance: 0.3, quantity: 1 },
    ],
    experienceValue: 5,
  },
  {
    id: 'raider',
    name: 'raider',
    description: 'a gaunt figure in scavenged armor. they don\'t speak. they just attack.',
    health: 30,
    attack: 5,
    defense: 3,
    speed: 4,
    terrain: ['forest', 'snow', 'ruins', 'battlefield'],
    minDistance: 6,
    loot: [
      { itemId: 'leather', chance: 0.4, quantity: 3 },
      { itemId: 'iron', chance: 0.3, quantity: 2 },
      { itemId: 'cloth', chance: 0.5, quantity: 2 },
      { itemId: 'meat', chance: 0.2, quantity: 1 },
    ],
    experienceValue: 15,
  },
  {
    id: 'wolfPack',
    name: 'wolf pack',
    description: 'three grey shapes moving in unison. coordinated. patient. hungry.',
    health: 45,
    attack: 7,
    defense: 2,
    speed: 6,
    terrain: ['forest', 'snow', 'deepSnow', 'mountain'],
    minDistance: 5,
    loot: [
      { itemId: 'fur', chance: 0.8, quantity: 5 },
      { itemId: 'meat', chance: 0.7, quantity: 4 },
      { itemId: 'teeth', chance: 0.5, quantity: 3 },
      { itemId: 'bone', chance: 0.4, quantity: 3 },
    ],
    experienceValue: 20,
  },
  {
    id: 'caveBear',
    name: 'cave bear',
    description: 'massive. scarred. it fills the cave mouth. the ground shakes when it moves.',
    health: 80,
    attack: 12,
    defense: 6,
    speed: 3,
    terrain: ['cave', 'mountain'],
    minDistance: 8,
    loot: [
      { itemId: 'fur', chance: 0.9, quantity: 10 },
      { itemId: 'meat', chance: 0.9, quantity: 8 },
      { itemId: 'teeth', chance: 0.7, quantity: 5 },
      { itemId: 'bone', chance: 0.6, quantity: 6 },
      { itemId: 'scales', chance: 0.2, quantity: 2 },
    ],
    experienceValue: 40,
  },
  {
    id: 'raiderCaptain',
    name: 'raider captain',
    description: 'better armed. better fed. a leader among thieves. iron blade and leather armor.',
    health: 60,
    attack: 9,
    defense: 5,
    speed: 4,
    terrain: ['ruins', 'battlefield', 'city', 'snow'],
    minDistance: 12,
    loot: [
      { itemId: 'iron', chance: 0.7, quantity: 5 },
      { itemId: 'leather', chance: 0.6, quantity: 4 },
      { itemId: 'steel', chance: 0.2, quantity: 2 },
      { itemId: 'cloth', chance: 0.5, quantity: 3 },
    ],
    experienceValue: 35,
  },
  {
    id: 'scavengerGang',
    name: 'scavenger gang',
    description: 'four figures picking through the rubble. they see you. they don\'t look friendly.',
    health: 50,
    attack: 8,
    defense: 3,
    speed: 4,
    terrain: ['ruins', 'city', 'battlefield'],
    minDistance: 10,
    loot: [
      { itemId: 'iron', chance: 0.5, quantity: 4 },
      { itemId: 'cloth', chance: 0.6, quantity: 5 },
      { itemId: 'leather', chance: 0.4, quantity: 3 },
      { itemId: 'coal', chance: 0.3, quantity: 3 },
    ],
    experienceValue: 30,
  },
  {
    id: 'theStarved',
    name: 'the starved',
    description: 'hollow eyes. hollow cheeks. they move wrong — too fast, too quiet. hunger has changed them into something else.',
    health: 70,
    attack: 11,
    defense: 2,
    speed: 8,
    terrain: ['city', 'ruins'],
    minDistance: 15,
    loot: [
      { itemId: 'teeth', chance: 0.7, quantity: 5 },
      { itemId: 'scales', chance: 0.3, quantity: 3 },
      { itemId: 'bone', chance: 0.6, quantity: 5 },
    ],
    experienceValue: 45,
  },
  {
    id: 'raiderKing',
    name: 'the raider king',
    description: 'a massive figure clad in scrap metal and bone. crowned with wire. his army stands behind him.',
    health: 280,
    attack: 16,
    defense: 8,
    speed: 5,
    terrain: ['city'],
    minDistance: 20,
    loot: [
      { itemId: 'alloy', chance: 1.0, quantity: 20 },
      { itemId: 'steel', chance: 1.0, quantity: 15 },
      { itemId: 'iron', chance: 1.0, quantity: 25 },
      { itemId: 'sulphur', chance: 1.0, quantity: 10 },
    ],
    experienceValue: 200,
  },
];

// ---------------------------------------------------------------------------
// Hidden areas
// ---------------------------------------------------------------------------

const hiddenAreas: HiddenAreaDef[] = [
  {
    id: 'hidden_undergroundNetwork',
    name: 'the underground tunnels',
    position: { x: 8, y: 28, z: -1 },
    size: { w: 6, h: 6 },
    revealCondition: 'flag.undergroundMapRevealed == true',
    terrain: 'cave',
  },
  {
    id: 'hidden_hermitCrypt',
    name: 'beneath the school',
    position: { x: 9, y: 11, z: -1 },
    size: { w: 3, h: 3 },
    revealCondition: 'flag.hermitPathRevealed == true',
    terrain: 'ruins',
  },
  {
    id: 'hidden_lakeChamber',
    name: 'beneath the lake',
    position: { x: 4, y: 34, z: -1 },
    size: { w: 3, h: 3 },
    revealCondition: 'flag.lakeSecretFound == true',
    terrain: 'cave',
  },
];

// ---------------------------------------------------------------------------
// Movement and supply costs
// ---------------------------------------------------------------------------

const movementCosts: Record<string, number> = {
  village: 1,
  snow: 2,
  forest: 3,
  deepSnow: 4,
  swamp: 5,
  ruins: 3,
  battlefield: 3,
  city: 3,
  cave: 4,
  mountain: 6,
  frozenLake: 4,
  cliff: Infinity,
};

const supplyCosts: Record<string, number> = {
  water: 1,
  curedMeat: 1,
};

// ---------------------------------------------------------------------------
// Assembled map config
// ---------------------------------------------------------------------------

export const mapConfig: MapConfig = {
  width: 40,
  height: 40,
  depth: 2, // surface + underground
  terrainTypes,
  pointsOfInterest,
  enemies,
  movementCosts,
  supplyCosts,
  hiddenAreas,
};
